spring:
 datasource:
  url: jdbc:mysql://123.56.182.213:3306/superplatform?useSSL=false&useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
  username: root
  password: ksjyhk
  driver-class-name: com.mysql.cj.jdbc.Driver
mybatis :
 mapper-locations : classpath:mapping/**/*.xml
server:
  port: 9008
